import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// 这些将在 Node.js 中运行
// 此处不要使用客户端代码 (浏览器 API, JSX ...)

/**
 * 创建侧边栏可以：
 - 创建有序的文档组
 - 为该组的每个文档呈现侧边栏
 - 提供前进/后退导航

 侧边栏可以从文件系统生成，也可以在此处明确定义

 根据需要创建任意数量的侧边栏
 */
const sidebars: SidebarsConfig = {
  // 默认情况下，Docusaurus 将根据 docs 文件夹结构生成侧边栏
  docSidebar: [{ type: "autogenerated", dirName: "." }],

  // 也可以手动创建侧边栏
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
