description = "猫猫的记录"
keywords = ["Hugo", "猫猫的博客", "计算机技巧", "二次元", "日常吐槽"]

[author]
name = "猫猫"
email = "neko@eroneko.eu.org"
link = "https://github.com/nek0x1a"
avatar = "/images/avatar.svg"

[app]
title = "猫的笔记本"

[header.title]
logo = "/images/logo.svg"

[home.profile]
enable = true
